name: Enforce Increment HPCDiag version number
on:
  pull_request:
    branches: [ main ]

jobs:
  enforce_increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: increment version number in main script
        run: |
          if ! git diff --exit-code origin/main -- Linux/src/gather_azhpc_vm_diagnostics.sh >/dev/null; then
            prev_version=$(git show origin/main:Linux/src/gather_azhpc_vm_diagnostics.sh | grep -Eo RELEASE_DATE=[^[:space:]]+ | cut -d'=' -f2)
            prev_date=$(echo "$prev_version" | cut -d- -f1)
            observed_version=$(cat Linux/src/gather_azhpc_vm_diagnostics.sh | grep -Eo RELEASE_DATE=[^[:space:]]+ | cut -d'=' -f2)
            latest_commit_date=$(git log --format=format:%cs --follow -- Linux/src/gather_azhpc_vm_diagnostics.sh | sort -r | head -1 | tr -d '-')

            if [[ "$latest_commit_date" > "$prev_date" ]]; then
              expected_version="$latest_commit_date"
            else
              expected_version=$(case "$prev_version" in
                *-*) 
                  prev_date=$(echo "$prev_version" | cut -d- -f1)
                  prev_minor=$(echo "$prev_version" | cut -d- -f2)
                  printf "%d-%02d" "$prev_date" $((prev_minor + 1))
                  ;;
                *) echo -n "$prev_version-01" ;;
              esac)
            fi

            if [ "$observed_version" != "$expected_version" ]; then
              echo "Expected version $expected_version. Please increment version number."
              false
            else
              echo "Version number is incremented correctly. Proceed."
              true
            fi
          else
            echo 'No changes to main script, skipping version number check.'
            true
          fi




